// Generated by tools/prepare_teaser.py from the verified source package.
const TEASER_MEDIA = Object.freeze({"featuredSlots": [119, 6, 76, 180, 40, 149, 222, 95, 166], "atlasColumns": 3, "gridColumns": 16, "clipSeconds": 3.2, "fps": 10});
